CREATE SEQUENCE municipio_seq INCREMENT 1 START 1;
CREATE SEQUENCE propriedade_seq INCREMENT 1 START 1;
CREATE SEQUENCE produto_seq INCREMENT 1 START 1;
CREATE SEQUENCE proprietario_seq INCREMENT 1 START 1;
